### ISSUE TITLE
Crash on picking up structure

### ISSUE THREAD

**Issue by Clockwork21** [WilloIzCitron/ArchiveDustry-Java#3]
**Describe the bug**
Game crashes when picking up "Reinforced Container" on Erekir campaign. 

**To Reproduce**
1. Place down a reinforced container
2. Move above it and press the "pickup cargo" key (default "[" )
3. Game crashes

**Expected behavior**
Picking up the structure

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version 16.0.1

**Additional context**
Game also crashes when placing the structure down (default "]" ). It can also be assumed that this issue also applies to any structure.

**Comment by Clockwork21** [comment]
Here's the crash report too:

java.lang.NullPointerException: Cannot read field "type" because "e.unit" is null
	at bluearchive.units.UnitSound.lambda$init$0(UnitSound.java:25)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.gen.PayloadUnit.dropBlock(PayloadUnit.java:544)
	at mindustry.gen.PayloadUnit.tryDropPayload(PayloadUnit.java:731)
	at mindustry.gen.PayloadUnit.dropLastPayload(PayloadUnit.java:558)
	at mindustry.input.InputHandler.payloadDropped(InputHandler.java:455)
	at mindustry.gen.Call.payloadDropped(Call.java:886)
	at mindustry.input.InputHandler.requestDropPayload(InputHandler.java:447)
	at mindustry.gen.Call.requestDropPayload(Call.java:1011)
	at mindustry.input.InputHandler.tryDropPayload(InputHandler.java:757)
	at mindustry.input.DesktopInput.updateMovement(DesktopInput.java:791)
	at mindustry.input.DesktopInput.update(DesktopInput.java:300)
	at mindustry.core.Control.update(Control.java:639)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by WilloIzCitron** [comment]
Oh that is problem of Unit sound.java, I will be fix that

**Comment by WilloIzCitron** [comment]
![image](https://github.com/WilloIzCitron/ArchiveDustry-Java/assets/49786146/e9c86eb8-210b-4c42-a53b-4ff597f66819)
this code from v1.1, and commit [e85967](https://github.com/WilloIzCitron/ArchiveDustry-Java/commit/e85967f2285928c93349a10243427a5cc530a2ea) was fixed this issue, stay tune for v1.2
